import { useNavigate } from "react-router-dom";
import { Shield, ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* ── Header ─────────────────────────────────────────────── */}
      <header className="h-16 border-b border-border/60 bg-white sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-6 h-full flex items-center justify-between">
          <button
            onClick={() => navigate("/")}
            className="flex items-center gap-2.5 hover:opacity-80 transition-opacity"
          >
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <Shield className="w-4.5 h-4.5 text-white" />
            </div>
            <span className="text-lg font-bold text-foreground tracking-tight">
              Verity
            </span>
          </button>
          <button
            onClick={() => navigate("/")}
            className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </button>
        </div>
      </header>

      {/* ── Content ────────────────────────────────────────────── */}
      <main className="flex-1 max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Effective Date: May 25, 2026</p>

        <div className="space-y-8 text-[15px] leading-relaxed text-foreground/85">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              These Terms of Service ("Terms") constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("User", "You"), and Verity ("Company", "We", "Us"). By accessing, browsing, or utilizing the Verity software and services ("Services"), you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree with all of these Terms, you are expressly prohibited from using the Services and must discontinue use immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">2. Description of Service and Limitations</h2>
            <p className="mb-3">
              Verity provides automated analytical tools designed to detect potential plagiarism and AI-generated text patterns. You acknowledge and agree to the following inherent limitations of the Services:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-2 mt-3">
              <li><strong>Probabilistic Nature:</strong> AI detection algorithms are probabilistic models and are subject to false positives and false negatives. Results should be interpreted strictly as indicators rather than definitive proof of authorship.</li>
              <li><strong>Database Coverage:</strong> Plagiarism detection is restricted to indexed, publicly available academic databases (e.g., OpenAlex, Crossref) and our internal repositories. The Services cannot detect similarities against paywalled content, unpublished manuscripts, or private databases to which We lack access.</li>
              <li><strong>Not Sole Basis for Decisions:</strong> The output generated by the Services shall not constitute the sole or primary basis for any disciplinary action, academic integrity violation charge, or employment decision. Human review and judgment are strictly required.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">3. Disclaimer of Warranties</h2>
            <p className="mb-3 uppercase font-semibold">
              THE SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
            </p>
            <p>
              We make no warranty that the Services will be uninterrupted, timely, secure, error-free, or completely accurate.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">4. Intellectual Property and License Grant</h2>
            <p className="mb-3">
              You retain all copyright and other intellectual property rights in and to the documents you upload to the Services ("User Content"). However, by uploading User Content, you grant Us the following licenses:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>
                <strong>For Analysis Scans:</strong> A limited, non-exclusive, revocable, royalty-free license to process the User Content in volatile memory strictly for the purpose of executing the requested analysis.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">5. Acceptable Use and Restrictions</h2>
            <p className="mb-3">As a condition of your use of the Services, you agree not to:</p>
            <ul className="list-disc list-inside space-y-2 ml-2">
              <li>Upload any content that is illegal, defamatory, or infringes upon the intellectual property rights of any third party.</li>
              <li>Attempt to reverse-engineer, decompile, or bypass the detection algorithms or security measures of the Services.</li>
              <li>Utilize automated scripts, scrapers, or bots to interact with the Services without express written authorization.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">6. Limitation of Liability</h2>
            <p className="uppercase font-semibold">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">7. Modifications to Terms</h2>
            <p>
              We reserve the right, in our sole discretion, to make changes or modifications to these Terms at any time. We will alert you about any changes by updating the "Effective Date" of these Terms, and you waive any right to receive specific notice of each such change.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">8. Contact Information</h2>
            <p>
              For inquiries or correspondence related to these Terms, please contact us via the project's official GitHub repository or designated support channels.
            </p>
          </section>
        </div>
      </main>

      {/* ── Footer ─────────────────────────────────────────────── */}
      <footer className="border-t border-border/40 bg-white py-6">
        <div className="max-w-7xl mx-auto px-6 flex items-center justify-between text-sm text-muted-foreground">
          <span>© 2026 Verity. All rights reserved.</span>
          <div className="flex items-center gap-6">
            <a href="/privacy" className="hover:text-foreground transition-colors">
              Privacy Policy
            </a>
            <a href="/terms" className="hover:text-foreground transition-colors font-medium text-foreground">
              Terms of Service
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
